blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
